import type { TargetRow } from '@/features/targets/types';

const TARGETS: TargetRow[] = [
  {
    id: 'g1',
    employee_name: 'خالد الدوسري',
    role_label: 'مبيعات',
    branch: 'نجران',
    contracts_target: 20,
    contracts_achieved: 23,
    collection_target: 180000,
    collection_achieved: 205000,
    avg_rating: 4.8,
    reward_amount: 2500,
  },
  {
    id: 'g2',
    employee_name: 'ريم الزهراني',
    role_label: 'مركز الاتصال',
    branch: 'نجران',
    contracts_target: 15,
    contracts_achieved: 16,
    collection_target: 120000,
    collection_achieved: 118000,
    avg_rating: 4.6,
    reward_amount: 1800,
  },
  {
    id: 'g3',
    employee_name: 'سعد القرني',
    role_label: 'مبيعات',
    branch: 'جازان',
    contracts_target: 18,
    contracts_achieved: 14,
    collection_target: 150000,
    collection_achieved: 132000,
    avg_rating: 4.3,
    reward_amount: 1200,
  },
  {
    id: 'g4',
    employee_name: 'نوال العمري',
    role_label: 'مدير فرع',
    branch: 'جازان',
    contracts_target: 25,
    contracts_achieved: 27,
    collection_target: 220000,
    collection_achieved: 241000,
    avg_rating: 4.7,
    reward_amount: 3000,
  },
  {
    id: 'g5',
    employee_name: 'ماجد الشهري',
    role_label: 'مبيعات',
    branch: 'شرورة',
    contracts_target: 12,
    contracts_achieved: 9,
    collection_target: 90000,
    collection_achieved: 71000,
    avg_rating: 4.0,
    reward_amount: 0,
  },
  {
    id: 'g6',
    employee_name: 'هيا الغامدي',
    role_label: 'مركز الاتصال',
    branch: 'حبونا',
    contracts_target: 10,
    contracts_achieved: 11,
    collection_target: 80000,
    collection_achieved: 84000,
    avg_rating: 4.5,
    reward_amount: 1500,
  },
];

export async function listTargets(): Promise<TargetRow[]> {
  return TARGETS;
}
